sudo: required
dist: trusty
git:
  depth: 1

language: node_js
node_js:
  - '6'
  - '7'
  - stable

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true

install:
  - npm install -g yo
  - npm install
  - npm link

before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
